nfdump:
  image: ghcr.io/pmh-only/nfdump:latest@sha256:b3fe50d58dd520fcc5f92e7a3d8196ebc021cc1ad55df2a9220e7ba3460d3871
nfdumpban:
  image: ghcr.io/pmh-only/nfdumpban:latest@sha256:257f2b5a746bf96c0996fbc38c47960bba358a20c412d4462fa80722db869914
pmacct:
  image: ghcr.io/pmh-only/pmacct:latest
