nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo@sha256:fbd2e3000f3b7034c6bd11966dd91950bd457e8f4b33c8f381114d5490d5578a
webserver:
  image: ghcr.io/pmh-only/webserver@sha256:094bb7399464eceb2834132ae6b1534e9656044097214ebb83a5e479a1d82a52
indexer:
  image: ghcr.io/pmh-only/indexer:latest@sha256:432ef0b14fad1169b4fb8d63d4517ffa64e0d6442f7938e651a0b99847153dd5
