nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo@sha256:fbd2e3000f3b7034c6bd11966dd91950bd457e8f4b33c8f381114d5490d5578a
webserver:
  image: ghcr.io/pmh-only/webserver@sha256:9ef4722aea374ad4e20fce8e73218d86e9fe044ce431978cb62fea98bad9c46a
indexer:
  image: ghcr.io/pmh-only/indexer:latest@sha256:f73858dc7593bcd7aee874a864b53dcda433d7a20d9dd992db9c41f72cc8026a
