nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo@sha256:fbd2e3000f3b7034c6bd11966dd91950bd457e8f4b33c8f381114d5490d5578a
webserver:
  image: ghcr.io/pmh-only/webserver:latest@sha256:269c96de4af19697d0a81daa985a6ac09b5344f92bd512b746265df0757c48a1
indexer:
  image: ghcr.io/pmh-only/indexer@sha256:44766aade2d52ebd764dbf7189ef3722cd1691636c7cfe9403f7f084422fadbd
