nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo@sha256:fbd2e3000f3b7034c6bd11966dd91950bd457e8f4b33c8f381114d5490d5578a
webserver:
  image: ghcr.io/pmh-only/webserver@sha256:646887d9dddfce5f94aac1d8e06c58ad9bf05983aeac13b3b64b485e7fd807bf
indexer:
  image: ghcr.io/pmh-only/indexer:latest@sha256:5c3058b299c66de54d22f156febc35600136ce309fd9b5ab47c47d451cb68ad7
