nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo:latest
webserver:
  image: ghcr.io/pmh-only/webserver:latest
indexer:
  image: ghcr.io/pmh-only/indexer:latest
ftpserver:
  image: ghcr.io/pmh-only/ftpserver:latest
rsyncserver:
  image: ghcr.io/pmh-only/rsyncserver:latest
