nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo@sha256:fbd2e3000f3b7034c6bd11966dd91950bd457e8f4b33c8f381114d5490d5578a
webserver:
  image: ghcr.io/pmh-only/webserver:latest@sha256:646887d9dddfce5f94aac1d8e06c58ad9bf05983aeac13b3b64b485e7fd807bf
indexer:
  image: ghcr.io/pmh-only/indexer@sha256:44766aade2d52ebd764dbf7189ef3722cd1691636c7cfe9403f7f084422fadbd
