nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo:latest@sha256:6e22da5028bb9d87210340eea515b5bdf2ae76a92084a69316373f8381437f81
webserver:
  image: ghcr.io/pmh-only/webserver:latest@sha256:e39b677740f7b261dbae5b663cd070acb8e5a2649fd6ec1cc7942b39dd74fc96
indexer:
  image: ghcr.io/pmh-only/indexer:latest@sha256:fd79362775a8947d97fd62a8050c8ba4eecf84a3cbbe8844f722355b06b52e5d
ftpserver:
  image: ghcr.io/pmh-only/ftpserver:latest@sha256:11ea0ee4aace95ae88ab724902974b56ae6c999871ff69d6eb29f51afe1a1116
rsyncserver:
  image: ghcr.io/pmh-only/rsyncserver:latest@sha256:cf56a95f4a2f5d4bc2c6de32c5eae60cec7a5d91567ed9c010b083004b34cd46
ipv6edge:
  image: ghcr.io/pmh-only/ipv6edge:latest@sha256:54b237ae7d92f7fdffbc7abf8abccb91814aa62ccefb000e8138413c651347cb
