nodeName: example
syncrepo:
  image: ghcr.io/pmh-only/syncrepo@sha256:fbd2e3000f3b7034c6bd11966dd91950bd457e8f4b33c8f381114d5490d5578a
webserver:
  image: ghcr.io/pmh-only/webserver@sha256:094bb7399464eceb2834132ae6b1534e9656044097214ebb83a5e479a1d82a52
indexer:
  image: ghcr.io/pmh-only/indexer:latest@sha256:b5520bace8cb3c30ec41fac5f7cd9d63b35fe76e178867c68f37dab38e96ee82
