apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: core
spec:
  selector:
    app: webserver
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http3
      protocol: UDP
      port: 443
      targetPort: 443
    - name: rsync-ssl
      protocol: TCP
      port: 874
      targetPort: 874
---
apiVersion: v1
kind: Service
metadata:
  name: rsyncserver
  namespace: core
spec:
  selector:
    app: rsyncserver
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ports:
    - name: rsync
      protocol: TCP
      port: 873
      targetPort: 873
