name: Build bwlimit images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - bwlimit/**

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (nfdump)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: bwlimit
          file: bwlimit/Dockerfile.nfdump
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/pmh-only/nfdump:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (nfdump-ban)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: bwlimit
          file: bwlimit/Dockerfile.nfdump-ban
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/pmh-only/nfdumpban:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (pmacct)
        uses: docker/build-push-action@v5
        with:
          push: true
          context: bwlimit
          file: bwlimit/Dockerfile.pmacct
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/pmh-only/pmacct:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
